# Generated by Django 4.1.6 on 2023-02-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField(max_length=100)),
                ('posicao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NomeAlternativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicas.musica')),
            ],
        ),
    ]
