# Generated by Django 4.1.6 on 2023-02-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='file',
            field=models.FileField(default='', upload_to='audio'),
            preserve_default=False,
        ),
    ]
