# Generated by Django 4.1.6 on 2023-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0002_musica_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='jogo',
            field=models.CharField(choices=[('1', 'um'), ('2', 'dois'), ('3', 'tres'), ('4', 'quatro')], default='um', max_length=2),
        ),
    ]
